Added static_quantizer (2)
TODO:
1. Quantization fails when padding parameter given as string (https://github.com/pytorch/pytorch/issues/76304)
2. implementing dynamic_quantizer for Conv layer, which is not supported natively in PyTorch (https://pytorch.org/docs/stable/quantization.html)
3.NotImplementedError: Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend. (in case of ResNet skip connections)
4. SiLU Layer cannot forward quant tensor